KS-21-1-extension
mametich/KotlinSprint pull request #102
Opened 2024-05-11 11:20 UTC by mametich

2024-05-15 05:05 UTC, ievetrovdev requested changes

2024-05-15 05:05 UTC, ievetrovdev commented on src/main/kotlin/lesson_21/lesson21_task1.kt
> +    for (letter in word) {
давай немного сократим код)
```
fun String.vowelCount(): Int {
    return count { it in "aeiou" }
}
```

2024-05-15 07:28 UTC, mametich commented on src/main/kotlin/lesson_21/lesson21_task1.kt
> +    for (letter in word) {
Omg)

2024-05-16 08:56 UTC, ievetrovdev approved these changes

2024-05-16 09:04 UTC, merged