KS-4-4 comparison
mametich/KotlinSprint pull request #19
Opened 2024-03-21 18:10 UTC by mametich

2024-03-22 07:19 UTC, ievetrovdev requested changes

2024-03-22 07:19 UTC, ievetrovdev commented on src/main/kotlin/lesson4/lesson4_task4.kt
> +    val isTrainingForArmsAndAbsMuscules = (dateOfDate % 2 != 0)
Идея правильная, только давай чуть чуть улучшим. Не будем дважды считать четность, а будем использовать оператор инвертирования.
Если хочешь использовать две переменные то можно сделать так `val isTrainingForBackAndLegs = ! isTrainingForArmsAndAbsMuscules`
А вообще можно сразу инвертировать в print

2024-03-22 16:31 UTC, mametich commented on src/main/kotlin/lesson4/lesson4_task4.kt
> +    val isTrainingForArmsAndAbsMuscules = (dateOfDate % 2 != 0)
Буду использовать 2 переменные

2024-03-23 05:44 UTC, ievetrovdev approved these changes
Да, хорошо

2024-03-23 07:01 UTC, merged