KS-5-3 expression
mametich/KotlinSprint pull request #23
Opened 2024-03-21 20:42 UTC by mametich

2024-03-23 08:36 UTC, ievetrovdev requested changes

2024-03-23 08:36 UTC, ievetrovdev commented on src/main/kotlin/lesson_5/lesson5_task3.kt
> +    if (firstNumberFromUser == firstCorrectNumber && secondNumberFromUser == secondCorrectNumber) {
А что будет, если пользователь введет выигрышные числа в обратном порядке?)

2024-03-23 08:36 UTC, ievetrovdev commented on src/main/kotlin/lesson_5/lesson5_task3.kt
> +    val firstNumberFromUser = readlnOrNull()!!.toInt()
Использование оператора !! подразумевает, что ты уверен в том, что значение не может быть null. Однако, если это не так, то приложение "упадет" с ошибкой. Поэтому этот оператор считается опасным и не рекомендуется использовать. Только в крайних случаях. 

Это противоречит основной идее безопасности типов в Kotlin, поэтому лучше использовать альтернативные способы обработки нулабельных значений. Такие как оператор безопасного вызова ?., элвис-оператор ?: или оператор let.

Но пока я рекомендую использовать более свежую функцию readln(). Метод под капотом обрабатывает нулябельность и все кастует в строку (в том числе null становится строкой “null”.

2024-03-23 08:41 UTC, mametich commented on src/main/kotlin/lesson_5/lesson5_task3.kt
> +    if (firstNumberFromUser == firstCorrectNumber && secondNumberFromUser == secondCorrectNumber) {
Да хотел задать вопрос что понимается ввести цифры в обратном порядке?
например, 36 обратно 63
или сначала пользователь ввел второе число а потом первое?

2024-03-24 17:39 UTC, ievetrovdev commented on src/main/kotlin/lesson_5/lesson5_task3.kt
> +    if (firstNumberFromUser == firstCorrectNumber && secondNumberFromUser == secondCorrectNumber) {
Да, ввод чисел в обратном порядке, подразумевается - поменять их местами

2024-03-24 17:39 UTC, ievetrovdev approved these changes
Теперь все верно

2024-03-25 05:54 UTC, merged