KS-7-1-for
mametich/KotlinSprint pull request #31
Opened 2024-03-26 10:41 UTC by mametich

2024-03-26 10:42 UTC, mametich commented
Добрый день Иван! Вроде догадался)

2024-03-26 15:03 UTC, ievetrovdev commented
> Добрый день Иван! Вроде догадался)

Добрый)

2024-03-26 15:05 UTC, ievetrovdev requested changes
Представь, гипотетически, что пароль будет состоять из гораздо большего количества символов) давай сделаем элегантнее  через цикл

2024-03-27 08:18 UTC, mametich commented
Иван, не могу догадаться как через цикл получить 6-значное число, просьба подсказать

2024-03-28 08:52 UTC, ievetrovdev commented
> Иван, не могу догадаться как через цикл получить 6-значное число, просьба подсказать

Ну так все верно теперь)

2024-03-28 08:52 UTC, ievetrovdev approved these changes

2024-03-28 10:35 UTC, merged