KS-9-5-list
mametich/KotlinSprint pull request #45
Opened 2024-03-30 19:48 UTC by mametich

2024-03-30 19:48 UTC, mametich commented
Добрый день Иван! не могу догадаться, просьба подсказать

2024-03-31 11:07 UTC, ievetrovdev requested changes

2024-03-31 11:07 UTC, ievetrovdev commented on src/main/kotlin/lesson_9/lesson9_task5.kt
> +        if (listOfIngredientsFromUser.contains(ingredientFromUser)) {
Текущая логика позволяет исключить повторы, но запрос на ввод нового ингредиента в случае обнаружения повторения не уменьшает общее количество итераций цикла. Это означает, что если пользователь введет дубликат, программа запросит меньше 5 уникальных ингредиентов. Посмотри или вспомни какая коллекция не умеет хранить повторы?
Вот в нее можно превратить проинициализированный введенными значениями список.

2024-03-31 11:07 UTC, ievetrovdev commented on src/main/kotlin/lesson_9/lesson9_task5.kt
> +    val listWithUpperCaseIngredients = sortedlistOfIngredientsFromUser.map {
Данное лямбда-выражение заменяет первую букву каждого элемента списка на заглавную. Вывод всех элементов списка в одну строку с разделителями запятыми и с заглавной буквы только для первого элемента можно достичь, используя joinToString с корректной обработкой первого элемента.

для изменения первой буквы только первого элемента списка на заглавную нужно использовать метод replaceFirstChar, примененный к результату joinToString.

2024-04-03 15:41 UTC, ievetrovdev approved these changes

2024-04-04 18:43 UTC, merged