KS-10-3-function
mametich/KotlinSprint pull request #48
Opened 2024-03-31 08:57 UTC by mametich

2024-04-03 07:45 UTC, ievetrovdev requested changes

2024-04-03 07:45 UTC, ievetrovdev commented on src/main/kotlin/lesson_10/lesson10_task3.kt
> +    val arrayOfSymbols = arrayOf(
Попробуй представить последовательность символов в виде диапазона. Подробнее тут https://ru.wikipedia.org/wiki/ASCII

2024-04-03 07:45 UTC, ievetrovdev commented on src/main/kotlin/lesson_10/lesson10_task3.kt
> +    for (i in 0..number) {
В цикле ты используешь (i in 0..number), это не гарантирует чередование цифр и спецсимволов по всей длине. Вместо этого, лучше использовать for (i in 1..number) и генерировать пароль, чередуя символы до достижения нужной длины.

Кроме того, эта реализация не обеспечивает строгое чередование цифр и спецсимволов, если длина пароля нечетная. Также, использование take(number) не гарантирует, что каждый второй символ будет спецсимволом, особенно если number — нечетное, попробуй посмотреть в сторону определения четности числа

2024-04-09 18:09 UTC, mametich commented on src/main/kotlin/lesson_10/lesson10_task3.kt
> +    for (i in 0..number) {
Добрый день Иван! Не совсем понял, если длина пароля, будет нечетное, например 5, то например код выдаст
5)8(3, вроде как чередуется и цифры и спецсимволы.

2024-04-10 11:56 UTC, ievetrovdev commented on src/main/kotlin/lesson_10/lesson10_task3.kt
> +    for (i in 0..number) {
> Добрый день Иван! Не совсем понял, если длина пароля, будет нечетное, например 5, то например код выдаст 5)8(3, вроде как чередуется и цифры и спецсимволы.

Приветствую, в целом все верно, предложенный алгоритм будет действительно чередовать символы, но закончит на цифре, что не совсем соответствует заданному условию чередования цифр и специальных символов до конца. Но это если сильно заморачиваться)

2024-04-10 11:56 UTC, ievetrovdev approved these changes

2024-04-10 12:01 UTC, merged