KS-1-5 create variables
mametich/KotlinSprint pull request #5
Opened 2024-03-12 19:51 UTC by mametich

2024-03-13 16:22 UTC, ievetrovdev requested changes

2024-03-13 16:22 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/Lesson1_task5.kt
> +    val hoursInSpace = (secondsInSpace % 3600)/60
Чтобы снизить риск ошибок, предлагаю все “голые” числа вынести в константу. Кроме того это [магические числа](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), что тоже не является хорошей практикой.

Также напоминаю, что в котлин все математические знаки обосабливаются пробелам

2024-03-13 18:31 UTC, mametich commented
Просьба подсказать что можно сделать. Начиная с пула реквеста КС-1-2 и до КС-1-5 конфликт, не могу замержить

2024-03-17 08:52 UTC, ievetrovdev approved these changes

2024-03-17 08:52 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/Lesson1_task5.kt
> +private const val SECONDS_IN_HOUR = 3600
В целом верно, но вот это число нужно было получить вычислением. На будущее)

2024-03-17 09:02 UTC, merged