KS-11-3-classes
mametich/KotlinSprint pull request #52
Opened 2024-04-07 19:13 UTC by mametich

2024-04-08 05:40 UTC, ievetrovdev requested changes

2024-04-08 05:40 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task3.kt
> +    var status: List<String> = listOf(
из этого списка мы не сможем понять какой конкретно сейчас статус у юзера, давай сделаем просто строкой

2024-04-08 05:40 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task3.kt
> +    var name: String,
судя по коду имя у юзера не меняется, давай его сделаем val

2024-04-08 05:40 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task3.kt
> +    var cover: String,
все свойства Room неизменны, нужно сделать их val

2024-04-08 05:40 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task3.kt
> +    ) {
забыл доделать функцию)

2024-04-10 07:15 UTC, ievetrovdev requested changes

2024-04-10 07:15 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task3.kt
> +        participant.name = name
нам нужно взять у `participant` имя, найти такого юзера в списке `listOfParticipant` и в этом списке обновить имя и статус на новые, иначе смысла в функции не много)

2024-04-11 18:39 UTC, mametich commented on src/main/kotlin/lesson_11/lesson11_task3.kt
> +        participant.name = name
Добрый день Иван! просьба подсказать в этом методе значит нужно передавать объект participant или нет? Откуда метод будет знать какой мне элемент обновить, если я в него передам только новое имя и новый статус.
И не могу понять как обновить имя и статус в списке через map или replace

2024-04-12 07:35 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task3.kt
> +        participant.name = name
текущая реализация вполне рабочая, но можно было передавать имя юзера для изменения и снаружи. изменение одного из полей класса у тебя реализовано верно, если нужно изменить больше полей, то можно сделать таким образом:
```
val itemIndex = listOfParticipant.indexOfFirst { it.name == oldName }
listOfParticipant[itemIndex] = Participant(
    status = "shemale",
    name = "newName"
)
```

2024-04-12 07:35 UTC, ievetrovdev approved these changes

2024-04-12 16:50 UTC, merged