KS-12-5-constuctor
mametich/KotlinSprint pull request #60
Opened 2024-04-21 10:44 UTC by mametich

2024-04-22 13:36 UTC, ievetrov requested changes

2024-04-22 13:36 UTC, ievetrov commented on src/main/kotlin/lesson_12/lesson12_task5.kt
> +        weatherOfDay5.isRainForAllDay = (i % 2) == 0
Для рандомизации Boolean есть еще такой экстеншн `Random.nextBoolean()`

2024-04-22 13:36 UTC, ievetrov commented on src/main/kotlin/lesson_12/lesson12_task5.kt
> +        fun printInformation(weatherOfDay: WeatherOfDay) {
неиспользуемый метод другого класса

2024-04-22 13:42 UTC, ievetrovdev requested changes
.

2024-04-23 16:38 UTC, ievetrovdev approved these changes

2024-04-23 17:47 UTC, merged